import { CRAFTING_EDGE_GUIDE } from "./crafting-edges-guide.js";
import { CORE_TIER_PROGRESSION } from "../scripts/crafting-model.js";
import { CRAFTING_RESOURCE_SOURCES } from "./crafting-resources.js";
import { PROFESSION_DEFINITIONS } from "./professions.js";
import { ENCHANTING_GUIDE } from "./enchanting-guide.js";

const esc = value => String(value ?? "").replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]);
const table = (head, rows) => `<table><thead><tr>${head.map(h => `<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>${rows.map(row => `<tr>${row.map(cell => `<td>${esc(cell)}</td>`).join("")}</tr>`).join("")}</tbody></table>`;
function page(index, name, content, gm = false) {
  return { _id: `wmGuidePage${String(index).padStart(5, "0")}`, name, type: "text", sort: index * 100000,
    ownership: { default: gm ? 0 : 2 }, title: { show: true, level: 1 },
    text: { format: 1, content: `<section class="cmt-rules-handbook"><header><h1>${esc(name)}</h1><p>${gm ? "GM reference" : "Player guide"}</p></header>${content}</section>` } };
}
const coreRows = Object.entries(CORE_TIER_PROGRESSION).map(([tier, values]) => [tier, `+${values.attack}`, `+${values.spellcasting}`, `+${values.armor} / +${values.saves}`]);
const resourceRows = CRAFTING_RESOURCE_SOURCES.map(item => [item.name, item.flags["pf2e-crafting-material-tiers"].resource.tier, item.system.level.value, `${item.system.price.value.gp} gp`, "0.2"]);

export const WRATHMAKER_PLAYER_GUIDE = {
  _id: "wmPlayerGuide001", name: "Player Guide", ownership: { default: 2 },
  pages: [
    page(1, "Welcome & quick reference", `<p>Use this guide for crafting, professions, equipment and exploration. The Workbench and character sheets show your campaign’s configured values.</p><ul><li>Choose one retrainable profession and use its Lore.</li><li>Craft, enchant, gather and disassemble through the Workbench.</li><li>Assign up to six artisans to earn teamwork bonuses.</li><li>Use the party Exploration tab for travel and shared activities.</li></ul><p>Artisan Marks are retired. Current crafting uses materials, native property runes, Crafting Edges and Masterstrokes.</p>`),
    page(2, "Professions", `<p>Choose one profession and retrain it into another at any time. It grants the named Lore, Additional Lore and Specialty Crafting for that profession, with trained proficiency at level 1, expert at 3, master at 7 and legendary at 15. Later levels do not grant additional professions.</p><p>Relevant profession checks retain a +2 circumstance bonus; it does not stack with another circumstance bonus. A relevant profession Lore is offered first for crafting and gathering. You may select another eligible skill.</p><h2>Core professions</h2><ul>${PROFESSION_DEFINITIONS.map(p => `<li>${esc(p.name)}</li>`).join("")}</ul><p>Specialty Crafting gives +1 circumstance to relevant Crafting checks, increasing to +2 at master Crafting proficiency. This does not stack with the profession’s +2 circumstance bonus. Optional specializations remain off by default.</p>`),
    page(3, "Hero & Nephilim Points", `<h2>Hero Points</h2><p>You can hold up to 10 Hero Points. Unspent points carry over between sessions. Use the normal character-sheet control; ordinary Hero Point spending rules still apply unless your GM says otherwise.</p><h2>Nephilim Bonds</h2><p>Open the three-dot menu beside Nephilim Bonds on the character sheet. Choose bonds at levels 5, 10, 15 and 20; unchosen earlier slots remain available. The control highlights when a choice is due.</p><h2>Nephilim Points</h2><p>The party has a separate shared tracker from 0 to 10 in its header. These points persist with the party. The GM determines when the party earns or spends these points and what benefits they provide.</p>`),
    page(4, "Equipment, Core materials & Apex items", `<p>A crafted item combines a PF2e base item with a Core material. Weapon materials grant attack bonuses; only Striking runes increase base weapon damage dice.</p>${table(["Tier", "Weapon attack", "Spell attack / DC", "Armor AC / saves"], coreRows)}<p>Materials do not grant weapon damage dice. Shields gain +3 Hardness and +30 HP per Core progression step. The displayed item includes applicable modifications.</p><h2>Omnipotentium</h2><p>Omni Iron, Omni Steel, Creation Steel, Fate Steel, Eternal Steel and Iron’s Blood are Tiers 1–6 of an alternative Core family for weapons and armour. Any tier bypasses Voidborn protection: other weapons and spells deal half damage to Voidborn creatures. Equipped Omni armour halves damage from Voidborn attackers. An active focus with an Omni frame also bypasses protection.</p><p>Omnipotentium is awarded only by the GM. It cannot be gathered and has no standard market or sale value. Find its ingots in their dedicated compendium; Void Protection has its own compendium.</p><h2>Spell Focus</h2><p>A held or worn focus with a Mana Gem Core grants its Core spellcasting bonus to spell attacks and DCs, not spell damage, slots or proficiency. Only the strongest active focus applies.</p><h2>Dragon Scales</h2><p>Scales enhance Metal or Leather/Hide armor. Hatchling, Juvenile, Youth, Adult, Ancient and Arch Dragon grant default resistance values 1, 4, 8, 12, 16 and 20. Black grants acid, Blue electricity, Green poison, Red fire and White cold resistance while the armor is equipped.</p><p>Scale quantities: buckler/small shield 1, light shield 2, standard shield 3, tower shield 4, fortress/oversized shield 5; clothing/light armour 2, medium 3, heavy 4, full plate/oversized heavy 5.</p><h2>Equipment size</h2><p>Medium is the default. Resource multipliers are Tiny ×0.5, Small ×0.75, Medium ×1, Large ×1.25, Huge ×1.5 and Gargantuan ×1.75. Round down, minimum one unit per requirement. Property runes always cost one Mana Gem each.</p><h2>Apex ability equipment</h2><p>These 30 worn items grant +1 to +5 to Strength, Dexterity, Constitution, Intelligence, Wisdom or Charisma. Wear and invest the item, then use its circled A on the character sheet. Different attributes can be active together; for the same attribute only the strongest applies. Belts, rings, amulets, circlets, sashes and brooches form the collection. These are campaign rewards, not a priced shop list.</p>`),
    page(5, "Resource catalogue", `<p>Resources are Equipment with the Precious tag. Each inventory unit is one Resource Unit, including named lots of crystals or scales. Five units weigh 1 Bulk; ten weigh 2 Bulk. Prices below are full unit values, before a sale discount. Existing older inventory copies may still appear as Treasure.</p><p>Tier levels are 1, 4, 8, 12, 16 and 20, with default level-based DCs 15, 19, 24, 30, 35 and 40. The actual attempt may have an adjustment.</p>${table(["Resource", "Tier", "Level", "Unit value", "Unit Bulk"], resourceRows)}`),
    page(6, "Crafting in the Workbench", `<ol><li>Choose the party, drop a supported base item into Craft, and select its recipe, Core material and Tier.</li><li>Add one lead artisan. Ordinary recipes can be crafted solo; selected enhancements may require an additional qualified artisan. Additional artisans contribute to the work. Dragon-scale reinforcement requires a Leatherwork artisan. </li><li>Review materials and days required.</li><li>Create the project to reserve Party Stash stock. Reservations prevent promising the same stock to multiple projects; they do not consume it.</li><li>Commit downtime and resolve Work Blocks. At completion, review and confirm the resource consumption and finished item.</li></ol><h2>Working together</h2><p>Up to six distinct artisans contribute. Each artisan after the lead grants +1 to Work Block rolls, up to +5. This stacks with profession bonuses and the existing teamwork time reduction. Each spends the same calendar downtime. Teamwork work rates are ×1 for 1–2 artisans, ×1.25 for 3–5, and ×1.5 for six. Fractional Progress carries between blocks. For a block of D days (1–5), the base success gives D Progress; critical success rolls a Crafting Edge (normally ceiling(1.5 × D)); failure gives zero for one day or floor(D ÷ 2) for longer blocks; critical failure gives zero. Apply the teamwork rate to that base Progress. Time estimates assume success.</p>${CRAFTING_EDGE_GUIDE}<p>Cancel a project to release unspent reservations. Archive finished projects to keep the list manageable. Deleting a record does not refund spent materials. Report a missing finished item to the GM rather than crafting a duplicate.</p>`),
    page(7, "Enchanting equipment", ENCHANTING_GUIDE),
    page(8, "Gathering, upgrades & disassembly", `<h2>Gather</h2><p>Use the Workbench Gather tab. Select a character, environment and resource; review its Tier, skill, DC, time and expected yield, then attempt the check. Region and environment can restrict available goods. One lead character rolls. On a success, add one material per party character to the Party Stash; on a critical success, add two per character. You can use relevant profession Lore instead of the listed skill.</p><h2>Upgrade</h2><p>Stow and uninvest a single crafted item, then drop it into Upgrade. Choose a new Core material or Tier, secondary materials and Tiers, or dragon scales. Legacy Mark records remain for historical reference and grant no benefits.</p><p>Replacement components require 25% fewer materials, rounded up per requirement, and 25% less component work. Unchanged components cost nothing. Old replaced materials are lost. Reservations and artisan teamwork follow normal projects; completion consumes the replacements and updates the original item, not a copy. Cancel to release the item and resources. Reserved items cannot be edited, equipped or dismantled. Use the latest project for recovery or disassembly.</p><p>Dragon-scale Resource Units cost 1.5 times the normal tier value. Mana crystals use normal tier prices.</p><h2>Disassemble</h2><p>Drop an item with a Core material and tier from your sheet or Party Stash into Disassemble. Review returns before confirming: the item is destroyed. Default recovery is 50%, rounded up separately for each material, Tier and variant. Recorded items use their project ledger; other compatible items show a standard-recipe estimate. Returns go to the selected Party Stash. Dismantled items cannot be salvaged twice or recovered as missing outputs.</p>`),
    page(9, "Flanking", `<p>First establish a normal opposite-side flank with two qualifying melee combatants in reach. Additional qualifying combatants can contribute from other sides.</p>${table(["Qualifying combatants", "Final target AC penalty"], [[2, "−2: Off-guard (Flanked)"], [3, "−3: Outnumbered (Flanked)"], ["4 or more", "−4: Surrounded (Flanked)"]])}<p>These are final penalties, not additions to the normal −2. Only qualifying melee attacks benefit; ranged attacks do not inherit this flanking penalty. Reach weapons count when they can reach the target. A creature unable to flank or an immune target follows its normal restrictions.</p><p>If the target is more than one size category larger than the largest qualifying flanker, the enhanced thresholds become six for −3 and eight for −4. A normal two-person flank still gives −2.</p>`),
    page(10, "Party travel & exploration", `<p>The party's Exploration tab combines normal exploration activities with travel setup, rider assignments and the daily plan. On foot, the slowest member limits shared Speed. Vehicle riders use transport Speed, while walkers can still slow the group. Pulled transport uses the slowest selected hauler, subject to the vehicle limit.</p>${table(["Shared Speed", "Activities per day"], [["10 feet or less", "½ (one activity over two days)"], ["15–25 feet", 1], ["30–40 feet", 2], ["45–55 feet", 3], ["60 feet or more", 4]])}<p>Assign Travel, Reconnoiter, Fortify Camp, Map the Area, Subsist or Other and mark activities Used as they finish. Save Travel Plan preserves choices; Begin Day & Share posts the plan. The sun button starts a new day.</p><h2>Express Rider house rule</h2><p>Select the character rolling Nature, pulling creatures and up to six affected party travellers, including walkers. The check uses the highest selected Will DC. Success or critical success increases affected overland Speeds by half for that day. Unaffected walkers and vehicle limits still constrain the group. This changes overland travel, not encounter Speed.</p>`),

  ],
};

export const WRATHMAKER_GM_GUIDE = {
  _id: "wmGMGuide0000001", name: "GM Companion", ownership: { default: 0 },
  pages: [
    page(1, "GM — Settings & campaign overrides", `<p>This companion is not player-facing. Keep its compendium and imported journal restricted. The Player Guide is safe to share at Observer permission; do not grant players Owner permission to GM notes.</p><p>Open Wrathmaker's control panel in Module Settings. The experimental Workbench is default-off; enable it when ready. Material rules, gathering and Hexploration have separate controls. Disabling a feature preserves saved selections. Enhanced flanking is permanent.</p><p>Edit material names, six-tier values, prices, rarities and bonus types; edit dragon colors and resistance values separately. The standard profession rules use a single retrainable profession, Additional Lore and profession-linked Specialty Crafting. Keep the optional profession setting disabled for these rules. Refresh All in Module Settings updates module-managed content and removes retired module effects. It first saves a GM-only journal in Wrathmaker Backups, then opens a completion report listing additions, removals, changes, skipped entries and failures. Custom GM settings are retained. Complete or cancel reserved upgrades before refreshing those items. The Player Guide is a shipped default reference, not a live mirror of custom settings: annotate an imported copy when changing campaign rules.</p>`, true),
    page(2, "GM — Resources, regions & awards", `<p>Set the gathering reward destination and the fallback environment and maximum Tier. Region-aware gathering can use supported scene/region terrain and level data; verify availability before play. Put mount and vehicle Actors in Wrathmaker Travel's Animals & Mounts and Vehicles & Transport folders.</p><p>Award Resource Units using the resource compendium. Do not halve their base prices merely to perform a half-price sale. Older Treasure documents are preserved; take care with existing project reservations before replacing stock. Apex items are campaign rewards whose prices are intentionally unspecified. Omnipotentium ingots are GM awards only, cannot be gathered, and have no standard market value. Apply the Voidborn creature trait to enable its protection. Omni weapons and active Omni-framed focuses bypass that half-damage protection; worn Omni armour halves damage from Voidborn attackers. Other resistances and immunities still apply.</p>`, true),
    page(4, "GM — Enchanting and teamwork", ENCHANTING_GUIDE + `<p>Each helper adds +1 to Work Block rolls, up to +5. This stacks with the profession bonus. Work rates remain ×1 for 1–2 artisans, ×1.25 for 3–5 and ×1.5 for six. Any critical success can trigger a Crafting Edge, including a result at least 10 above the DC. Masterstroke opportunities occur only on a qualifying final block. Roll the weapon or equipment Masterstroke table automatically, rerolling incompatible results. Each item keeps one Masterstroke through upgrades. Limited benefits apply to the first eligible roll or hit, and their uses follow the item when transferred. Overwhelming Impact offers a prone or push choice.</p>`, true),
    page(3, "GM — Custom items, recovery & adjudication", `<p>The GM Item Creator creates world items without project costs. Choose the Core material, tier, components and artisan name. New custom items go into GM crafted items with no player ownership. Folder visibility follows the items inside; grant access deliberately when awarding an item.</p><p>Recover Missing Item recreates a completed project's missing output without charging again, while checking for an existing output. Recovery is blocked after dismantling. Do not use recovery to award duplicates.</p><p>The module does not itself define Nephilim Point powers. Define awards and expenditures for your campaign. Back up the world before broad changes to inventory or campaign configuration.</p>`, true),
  ],
};
