import { CORE_TIER_PROGRESSION } from "../scripts/crafting-model.js";
import { CRAFTING_RESOURCE_SOURCES } from "./crafting-resources.js";
import { PROFESSION_DEFINITIONS, SPECIALTIES_BY_PROFESSION } from "./professions.js";
import { ARTISAN_MARK_DEFINITIONS } from "./artisan-marks.js";

const esc = value => String(value ?? "").replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]);
const table = (head, rows) => `<table><thead><tr>${head.map(h => `<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>${rows.map(row => `<tr>${row.map(cell => `<td>${esc(cell)}</td>`).join("")}</tr>`).join("")}</tbody></table>`;
function page(index, name, content, gm = false) {
  return { _id: `wmGuidePage${String(index).padStart(5, "0")}`, name, type: "text", sort: index * 100000,
    ownership: { default: gm ? 0 : 2 }, title: { show: true, level: 1 },
    text: { format: 1, content: `<section class="cmt-rules-handbook"><header><h1>${esc(name)}</h1><p>Wrathmaker · ${gm ? "GM reference" : "Player guide"}</p></header>${content}</section>` } };
}
const coreRows = Object.entries(CORE_TIER_PROGRESSION).map(([tier, values]) => [tier, `+${values.attack}`, values.weaponDice, `+${values.spellcasting}`, `+${values.armor} / +${values.saves}`, values.capacity]);
const resourceRows = CRAFTING_RESOURCE_SOURCES.map(item => [item.name, item.flags["pf2e-crafting-material-tiers"].resource.tier, item.system.level.value, `${item.system.price.value.gp} gp`, "0.2"]);

function markList(professionId, specializationId = "") {
  const marks = ARTISAN_MARK_DEFINITIONS.filter(mark => mark.professionId === professionId && (mark.specializationId || "") === specializationId);
  return `<div class="cmt-guide-marks">${marks.map(mark => `<article data-mark-id="${esc(mark.id)}"><h4>${esc(mark.name)}</h4><p><strong>${esc(mark.grade)} · ${mark.capacityCost} Capacity</strong> · Anchor Tier ${mark.minimumAnchorTier}+ · ${esc(mark.categories.join(", "))}</p><p>${esc(mark.effectSummary)}</p><details><summary>Requirements & source</summary><p>${esc(mark.profession)} — ${esc(mark.specialisation || "Universal")} · Core Tier ${mark.minimumTier}+${mark.requiresCoreTierAnchors ? "; Core-tier Anchor required" : ""}</p><p>Anchors: ${esc(mark.anchorSlotTypes.join(", "))}. ${mark.materialUnits ? `${mark.materialUnits} material unit(s): ${esc(mark.requiredMaterialIds.join(", "))}.` : "Workshop consumables only."}</p></details></article>`).join("")}</div>`;
}

export const WRATHMAKER_PLAYER_GUIDE = {
  _id: "wmPlayerGuide001", name: "Wrathmaker — Player Guide", ownership: { default: 2 },
  pages: [
    page(1, "Welcome & quick reference", `<p>Your central reference for Wrathmaker's additions to Pathfinder 2e. Use the journal's page list to jump to a topic. These are campaign house rules, not replacements for every PF2e rule.</p><p>The tables show the module's current defaults. Your character sheet, item and Workbench show your campaign's configured values; ask the GM if they differ. Optional features may not be enabled.</p><ul><li>Choose a profession on your character sheet; its feats appear under Profession Feats.</li><li>Track Hero Points on your character and Nephilim Points on the party.</li><li>Use the party Exploration tab for travel and the Workbench for crafting, gathering and disassembly.</li><li>Look under Pathfinder 2E Wrathmaker in Compendium Packs for the additional items, professions and guides.</li></ul><p>The Mark pages at the end include sources and descriptions. A listed Mark is a reference, not an automatic grant: your item and artisan must qualify.</p>`),
    page(2, "Professions & specialisations", `<p>Choose one starting profession at level 1. It grants its named Lore, Additional Lore, Specialty Crafting and its determined bonus feat. Profession Feats are grouped beneath their parent profession.</p>${table(["Profession", "Additional feat"], PROFESSION_DEFINITIONS.map(p => [p.name, p.bonusFeatName || "Not yet determined"]))}<p>Lore proficiency is trained at level 1, expert at 3, master at 7 and legendary at 15. At levels 4, 10 and 16, choose a specialty of your starting profession or learn a new profession. Specialty Lore follows the same proficiency progression.</p><p>Relevant profession checks receive a +2 circumstance bonus. This does not stack with another circumstance bonus such as Specialty Crafting on the same check. Each specialisation has Signature, Mastery and Legacy sections; use its current description, and do not treat unresolved placeholders as granted benefits.</p>${PROFESSION_DEFINITIONS.map(p => `<h2>${esc(p.name)}</h2><ul>${(SPECIALTIES_BY_PROFESSION[p.id] ?? []).map(s => `<li><strong>${esc(s.name ?? s.label)}</strong>: ${esc(s.description)}</li>`).join("")}</ul>`).join("")}`),
    page(3, "Hero & Nephilim Points", `<h2>Hero Points</h2><p>You can hold up to 10 Hero Points. Unspent points carry over between sessions. Use the normal character-sheet control; ordinary Hero Point spending rules still apply unless your GM says otherwise.</p><h2>Nephilim Points</h2><p>The party has a separate shared tracker from 0 to 10 in its header. These points persist with the party. Wrathmaker tracks the total but does not define automatic powers or spending benefits; your GM explains when they are earned or spent.</p>`),
    page(4, "Equipment, Core materials & Apex items", `<p>A crafted item combines a PF2e base item, a Core material and optional Artisan Marks. Core progression replaces rune-style progression on that item; do not add the replaced rune benefits a second time.</p>${table(["Tier", "Weapon attack", "Extra damage dice", "Spell attack / DC", "Armor AC / saves", "Capacity"], coreRows)}<p>Weapon dice are additional dice, not flat damage. Shields gain +3 Hardness and +30 HP per Core progression step. The displayed item includes applicable modifications.</p><h2>Spell Focus</h2><p>A held Metal or Wood focus grants its Core spellcasting bonus to spell attacks and DCs, not spell damage, slots or proficiency. Only the strongest held focus applies.</p><h2>Dragon Scales</h2><p>Scales enhance Metal or Leather/Hide armor. Hatchling, Juvenile, Youth, Adult, Ancient and Arch Dragon grant default resistance values 1, 4, 8, 12, 16 and 20. Black grants acid, Blue electricity, Green poison, Red fire and White cold resistance while the armor is equipped.</p><h2>Apex ability equipment</h2><p>Wrathmaker's 30 worn items grant +1 to +5 to Strength, Dexterity, Constitution, Intelligence, Wisdom or Charisma. Wear and invest the item, then use its circled A on the character sheet. Different attributes can be active together; for the same attribute only the strongest applies. Belts, rings, amulets, circlets, sashes and brooches form the collection. These are campaign rewards, not a priced shop list.</p>`),
    page(5, "Resource catalogue", `<p>Resources are Equipment with the Precious tag. Each inventory unit is one Resource Unit, including named lots of crystals or scales. Five units weigh 1 Bulk; ten weigh 2 Bulk. Prices below are full unit values, before a sale discount. Existing older inventory copies may still appear as Treasure.</p><p>Tier levels are 1, 4, 8, 12, 16 and 20, with default level-based DCs 15, 19, 24, 30, 35 and 40. The actual attempt may have an adjustment.</p>${table(["Resource", "Tier", "Level", "Unit value", "Unit Bulk"], resourceRows)}`),
    page(6, "Crafting in the Workbench", `<ol><li>Choose the party, drop a supported base item into Craft, and select its recipe, Core material and Tier.</li><li>Add one lead artisan. Every supported recipe can be crafted solo. Additional material specialists unlock their eligible Marks and combinations rather than access to the base item.</li><li>Choose Marks and compatible Anchors. Review materials, Capacity and required progress.</li><li>Create the project to reserve Party Stash stock. Reservations prevent promising the same stock to multiple projects; they do not consume it.</li><li>Commit downtime and resolve Work Blocks. At completion, review and confirm the resource consumption and finished item.</li></ol><h2>Working together</h2><p>Up to six distinct artisans contribute. Each spends the same calendar downtime. A successful one-day block produces one Progress per artisan: six artisans produce six Progress. For a block of D days (1–5), success gives D Progress per artisan; critical success gives ceiling(1.5 × D); failure gives zero for one day or floor(D ÷ 2) for longer blocks; critical failure gives zero. Time estimates assume success.</p><p>Cancel a project to release unspent reservations. Archive finished projects to keep the list manageable. Deleting a record does not refund spent materials. Report a missing finished item to the GM rather than crafting a duplicate.</p>`),
    page(7, "Artisan Marks & activations", `<p>Click an artisan to choose Marks. Sources identify the profession and specialisation. Item compatibility, Anchors, minimum Tiers, stock and stacking rules still apply; extra artisans do not automatically activate every synergy.</p>${table(["Grade", "Capacity cost", "Minimum Anchor Tier"], [["Minor", 0, 1], ["Standard", 1, 2], ["Major", 2, 3], ["Superior", 3, 4]])}<p>Only one zero-Capacity Mark is allowed per item. Capacity is shared across all artisans. Secondary structural material must normally be at least Core Tier minus two. Some Marks impose stricter requirements.</p><p>Make & Marks on the finished item records the Core, applied Marks and makers. Chat badges provide compact provenance. Structure-only and consumable-only Marks do not appear in the equipment picker.</p><p>Some numerical effects are automated, others require their condition to be selected or resolved during play. For explicit action costs, Add Mark Actions to Wielder creates native action entries on the owning character. These post the rules; they do not automatically resolve targets, damage or limited uses. An unspecified action cost is not permission to activate for free. Remove a linked action when its item is lost or transferred.</p>`),
    page(8, "Gathering & disassembly", `<h2>Gather</h2><p>Use the Workbench Gather tab. Select a character, environment and resource; review its Tier, skill, DC, time and expected yield, then attempt the check. Region and environment can restrict available goods. Rewards go to the party or gathering character according to your campaign settings.</p><h2>Disassemble</h2><p>Drop a Wrathmaker-formatted item from your sheet or Party Stash into Disassemble. Review returns before confirming: the item is destroyed. Default recovery is 90%, rounded down separately for each material, Tier and variant. Recorded items use their project ledger; other compatible items show a standard-recipe estimate. Returns go to the selected Party Stash. Dismantled items cannot be salvaged twice or recovered as missing outputs.</p>`),
    page(9, "Flanking", `<p>First establish a normal opposite-side flank with two qualifying melee combatants in reach. Additional qualifying combatants can contribute from other sides.</p>${table(["Qualifying combatants", "Final target AC penalty"], [[2, "−2: Off-guard (Flanked)"], [3, "−3: Outnumbered (Flanked)"], ["4 or more", "−4: Surrounded (Flanked)"]])}<p>These are final penalties, not additions to the normal −2. Only qualifying melee attacks benefit; ranged attacks do not inherit this flanking penalty. Reach weapons count when they can reach the target. A creature unable to flank or an immune target follows its normal restrictions.</p><p>If the target is more than one size category larger than the largest qualifying flanker, the enhanced thresholds become six for −3 and eight for −4. A normal two-person flank still gives −2.</p>`),
    page(10, "Party travel & exploration", `<p>The party's Exploration tab combines normal exploration activities with travel setup, rider assignments and the daily plan. On foot, the slowest member limits shared Speed. Vehicle riders use transport Speed, while walkers can still slow the group. Pulled transport uses the slowest selected hauler, subject to the vehicle limit.</p>${table(["Shared Speed", "Activities per day"], [["10 feet or less", "½ (one activity over two days)"], ["15–25 feet", 1], ["30–40 feet", 2], ["45–55 feet", 3], ["60 feet or more", 4]])}<p>Assign Travel, Reconnoiter, Fortify Camp, Map the Area, Subsist or Other and mark activities Used as they finish. Save Travel Plan preserves choices; Begin Day & Share posts the plan. The sun button starts a new day.</p><h2>Express Rider house rule</h2><p>Select the character rolling Nature, pulling creatures and up to six affected party travellers, including walkers. The check uses the highest selected Will DC. Success or critical success increases affected overland Speeds by half for that day. Unaffected walkers and vehicle limits still constrain the group. This changes overland travel, not encounter Speed.</p>`),
    ...PROFESSION_DEFINITIONS.map((profession, index) => page(index + 11, `${profession.name} — Specialisation reference`,
      `<p>Campaign descriptions, not a promise that every effect is automated. Check the current profession entry for any local changes.</p><h2>Universal Artisan Marks</h2>${markList(profession.id)}` +
      (SPECIALTIES_BY_PROFESSION[profession.id] ?? []).map(specialty => `<h2>${esc(specialty.label)}</h2><p>${esc(specialty.description)}</p>${Object.entries(specialty.stages).map(([stage, feature]) => `<h3>${esc(stage[0].toUpperCase() + stage.slice(1))} — ${esc(feature.label)}</h3><p>${esc(feature.description)}</p>`).join("")}<h3>Artisan Marks</h3>${markList(profession.id, specialty.id)}`).join(""))),
  ],
};

export const WRATHMAKER_GM_GUIDE = {
  _id: "wmGMGuide0000001", name: "Wrathmaker — GM Companion", ownership: { default: 0 },
  pages: [
    page(1, "GM — Settings & campaign overrides", `<p>This companion is not player-facing. Keep its compendium and imported journal restricted. The Player Guide is safe to share at Observer permission; do not grant players Owner permission to GM notes.</p><p>Open Wrathmaker's control panel in Module Settings. The experimental Workbench is default-off; enable it when ready. Material rules, gathering and Hexploration have separate controls. Disabling a feature preserves saved selections. Enhanced flanking is permanent.</p><p>Edit material names, six-tier values, prices, rarities and bonus types; edit dragon colors and resistance values separately. Edit profession specialisations and their Signature, Mastery and Legacy descriptions. The Player Guide is a shipped default reference, not a live mirror of custom settings: annotate an imported copy when changing campaign rules.</p>`, true),
    page(2, "GM — Resources, regions & awards", `<p>Set the gathering reward destination and the fallback environment and maximum Tier. Region-aware gathering can use supported scene/region terrain and level data; verify availability before play. Put mount and vehicle Actors in Wrathmaker Travel's Animals & Mounts and Vehicles & Transport folders.</p><p>Award Resource Units using the resource compendium. Do not halve their base prices merely to perform a half-price sale. Older Treasure documents are preserved; take care with existing project reservations before replacing stock. Apex items are campaign rewards whose prices are intentionally unspecified.</p>`, true),
    page(3, "GM — Custom items, recovery & adjudication", `<p>The GM Item Creator creates world items without project costs. Use typed maker names, compatible Marks and Anchors. Exceeding Capacity requires confirmation; the one-free-Mark restriction still applies.</p><p>Recover Missing Item recreates a completed project's missing output without charging again, while checking for an existing output. Recovery is blocked after dismantling. Do not use recovery to award duplicates.</p><p>Mark automation remains partial. Confirm unspecified activation costs, target selection, limited uses and GM-approved effects before play. Native Mark Actions are rules/chat entries, not proof an effect has resolved. Do not assume structure or Kingdom benefits affect personal equipment.</p><p>The module does not itself define Nephilim Point powers. Define awards and expenditures for your campaign. Back up the world before broad changes to inventory or campaign configuration.</p>`, true),
  ],
};
